linters:
  enable-all: true
  disable:
    - exhaustruct
    - exportloopref
    - forbidigo
    - gochecknoglobals
    - nestif
    - nlreturn
    - paralleltest
    - revive
    - stylecheck
    - varnamelen
