name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          go test

      - run: mkdir -p dist/

      - name: Build linux-amd64
        run: |
          go build -o dist/systemd-age-creds-amd64
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Build linux-arm64
        run: |
          go build -o dist/systemd-age-creds-arm64
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: systemd-age-creds
          path: dist/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
